name: record_android
description: Android specific implementation for record package called by record_platform_interface.
version: 1.0.0-beta.2
publish_to: none
#homepage: https://github.com/llfbandit/record/tree/master/record_android

environment:
  sdk: ">=2.15.1 <4.0.0"
  flutter: ">=2.8.1"

dependencies:
  flutter:
    sdk: flutter

# dependency_overrides:
  record_platform_interface:
    path: ../record_platform_interface

flutter:
  plugin:
    implements: record
    platforms:
      android:
        package: com.llfbandit.record
        pluginClass: RecordPlugin
