name: record
description: Audio recorder from microphone to a given file path with multiple codecs, bit rate and sampling rate options.
version: 5.0.0-beta.2
publish_to: none
#homepage: https://github.com/llfbandit/record/tree/master/record

environment:
  sdk: ">=2.15.1 <4.0.0"
  flutter: ">=2.8.1"

dependencies:
  flutter:
    sdk: flutter

  uuid: ^4.0.0

#dependency_overrides:
  record_platform_interface:
    git:
      url: 'https://github.com/BojanicSara/record.git'
      path: './record_platform_interface/'
  record_web:
    git:
      url: 'https://github.com/BojanicSara/record.git'
      path: './record_web/'
      ref: 'update-dependencies'
  record_windows:
    git:
      url: 'https://github.com/BojanicSara/record.git'
      path: './record_windows/'
  record_linux:
    git:
      url: 'https://github.com/BojanicSara/record.git'
      path: './record_linux/'
  record_android:
    git:
      url: 'https://github.com/BojanicSara/record.git'
      path: './record_android/'
  record_darwin:
    git:
      url: 'https://github.com/BojanicSara/record.git'
      path: './record_darwin/'
      ref: 'ios-issues-fixed'

dev_dependencies:
  # https://pub.dev/packages/flutter_lints
  flutter_lints: ^2.0.0

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        default_package: record_android
      ios:
        default_package: record_darwin
      web:
        default_package: record_web
      windows:
        default_package: record_windows
      macos:
        default_package: record_darwin
      linux:
        default_package: record_linux
